apiVersion: apps/v1
kind: Deployment
metadata:
  name: img2json-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: img2json-deployment
  template:
    metadata:
      labels:
        app: img2json-deployment
    spec:
      containers:
      - name: img2json
        image: 192.168.179.25:5000/img2json:10
        imagePullPolicy: Always
        ports:
        - containerPort: 5002
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: img2json-service
  name: img2json-service
spec:
  ports:
  - port: 5002
    nodePort: 30113
  selector:
    app: img2json-deployment
  type: LoadBalancer
